"""
Create Retrain Issue Tool

再学習Issue作成ツール
"""

import json
import logging
import os
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from uuid import uuid4

logger = logging.getLogger(__name__)

# 有効な再学習理由
VALID_REASONS = [
    "data_change",
    "code_change",
    "schedule",
    "metrics_degradation",
    "drift_detection",
    "manual",
]


def create_retrain_issue(
    model_name: str,
    reason: str,
    trigger_details: Optional[Dict[str, Any]] = None,
    repo_owner: Optional[str] = None,
    repo_name: Optional[str] = None,
) -> Dict[str, Any]:
    """
    再学習Issueを作成

    Args:
        model_name: モデル名
        reason: 再学習理由（data_change, code_change, schedule, metrics_degradation, drift_detection, manual）
        trigger_details: トリガー詳細情報（オプション）
        repo_owner: リポジトリオーナー（省略時は環境変数から取得）
        repo_name: リポジトリ名（省略時は環境変数から取得）

    Returns:
        Issue作成結果辞書
    """
    logger.info(f"Creating retrain issue for model: {model_name}, reason: {reason}")

    # パラメータ検証
    if not model_name:
        raise ValueError("model_name must not be empty")

    if not reason:
        raise ValueError("reason must not be empty")

    if reason not in VALID_REASONS:
        raise ValueError(f"Invalid reason: {reason}. Must be one of: {', '.join(VALID_REASONS)}")

    try:
        timestamp = datetime.now(timezone.utc).isoformat()
        issue_id = str(uuid4())[:8]

        # リポジトリ情報を取得
        owner = repo_owner or os.environ.get("GITHUB_REPO_OWNER", "")
        repo = repo_name or os.environ.get("GITHUB_REPO_NAME", "")

        # Issue本文を生成
        title, body = _generate_issue_content(
            model_name=model_name,
            reason=reason,
            trigger_details=trigger_details,
            timestamp=timestamp,
        )

        env = os.environ.get("MLOPS_ENV", "development")
        github_token = os.environ.get("GITHUB_TOKEN")

        # 開発/テスト環境ではモック
        if env in ["development", "test"] or not github_token or not owner or not repo:
            logger.info("Using mock issue creation (dev/test environment)")
            return _mock_create_issue(
                model_name=model_name,
                reason=reason,
                title=title,
                body=body,
                issue_id=issue_id,
                timestamp=timestamp,
                owner=owner or "mock-owner",
                repo=repo or "mock-repo",
            )

        # 本番環境：実際にGitHub Issueを作成
        return _real_create_issue(
            owner=owner,
            repo=repo,
            title=title,
            body=body,
            model_name=model_name,
            reason=reason,
            issue_id=issue_id,
            timestamp=timestamp,
            github_token=github_token,
        )

    except Exception as e:
        logger.error(f"Failed to create retrain issue: {e}")
        raise ValueError(f"Failed to create retrain issue: {e}")


def _generate_issue_content(
    model_name: str,
    reason: str,
    trigger_details: Optional[Dict[str, Any]],
    timestamp: str,
) -> tuple[str, str]:
    """Issue タイトルと本文を生成"""
    # 理由に応じたラベルとアイコン
    reason_info = {
        "data_change": {"icon": "📊", "label": "New Data Available"},
        "code_change": {"icon": "💻", "label": "Code Updated"},
        "schedule": {"icon": "⏰", "label": "Scheduled Retrain"},
        "metrics_degradation": {"icon": "📉", "label": "Performance Degraded"},
        "drift_detection": {"icon": "🔀", "label": "Data Drift Detected"},
        "manual": {"icon": "👤", "label": "Manual Request"},
    }

    info = reason_info.get(reason, {"icon": "🔄", "label": reason})
    title = f"{info['icon']} [Retrain Request] {model_name} - {info['label']}"

    # 本文を生成
    body_lines = [
        f"## Retraining Request: {model_name}",
        "",
        "### Trigger Information",
        f"- **Reason**: {reason}",
        f"- **Detected at**: {timestamp}",
        "",
    ]

    # トリガー詳細があれば追加
    if trigger_details:
        body_lines.extend(["### Trigger Details", "```json"])
        body_lines.append(json.dumps(trigger_details, indent=2, ensure_ascii=False))
        body_lines.extend(["```", ""])

    # 推奨アクション
    body_lines.extend(
        [
            "### Recommended Actions",
            "1. Review trigger conditions and verify the need for retraining",
            "2. Check data quality and availability",
            "3. Approve and initiate retraining workflow",
            "",
            "---",
            "*Auto-generated by MLOps MCP Server*",
        ]
    )

    body = "\n".join(body_lines)
    return title, body


def _mock_create_issue(
    model_name: str,
    reason: str,
    title: str,
    body: str,
    issue_id: str,
    timestamp: str,
    owner: str,
    repo: str,
) -> Dict[str, Any]:
    """モックIssue作成"""
    mock_issue_number = 999

    return {
        "status": "success",
        "message": "Retrain issue created (mock)",
        "issue_result": {
            "issue_id": f"mock-issue-{issue_id}",
            "issue_number": mock_issue_number,
            "model_name": model_name,
            "reason": reason,
            "title": title,
            "body_preview": body[:200] + "..." if len(body) > 200 else body,
            "html_url": f"https://github.com/{owner}/{repo}/issues/{mock_issue_number}",
            "repository": f"{owner}/{repo}",
            "labels": ["retrain", "mlops", "automated"],
            "timestamp": timestamp,
            "mock": True,
        },
    }


def _real_create_issue(
    owner: str,
    repo: str,
    title: str,
    body: str,
    model_name: str,
    reason: str,
    issue_id: str,
    timestamp: str,
    github_token: str,
) -> Dict[str, Any]:
    """実際のGitHub Issue作成"""
    api_url = f"https://api.github.com/repos/{owner}/{repo}/issues"

    payload = {
        "title": title,
        "body": body,
        "labels": ["retrain", "mlops", "automated"],
    }

    data = json.dumps(payload).encode("utf-8")

    req = urllib.request.Request(
        api_url,
        data=data,
        headers={
            "Accept": "application/vnd.github.v3+json",
            "Authorization": f"token {github_token}",
            "Content-Type": "application/json",
            "User-Agent": "MLOps-MCP-Server",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            response_data = json.loads(response.read().decode("utf-8"))

            return {
                "status": "success",
                "message": "Retrain issue created successfully",
                "issue_result": {
                    "issue_id": str(response_data.get("id", issue_id)),
                    "issue_number": response_data.get("number"),
                    "model_name": model_name,
                    "reason": reason,
                    "title": title,
                    "html_url": response_data.get("html_url", ""),
                    "repository": f"{owner}/{repo}",
                    "labels": ["retrain", "mlops", "automated"],
                    "timestamp": timestamp,
                    "mock": False,
                },
            }

    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8") if e.fp else ""
        raise ValueError(f"GitHub API error ({e.code}): {error_body}")
    except urllib.error.URLError as e:
        raise ValueError(f"Failed to connect to GitHub: {e}")
